AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 File-Sharing System

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        TABLE_NAME: !Ref FileShareTable
        FILE_BUCKET: !Ref FileStorageBucket
    Layers:
      - !Ref SharedLayer

Resources:

  # ---- DynamoDB ----
  FileShareTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-table'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
        - AttributeName: GSI2PK
          AttributeType: S
        - AttributeName: GSI2SK
          AttributeType: S
        - AttributeName: GSI3PK
          AttributeType: S
        - AttributeName: GSI3SK
          AttributeType: S
        - AttributeName: GSI4PK
          AttributeType: S
        - AttributeName: GSI4SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2PK
              KeyType: HASH
            - AttributeName: GSI2SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI3
          KeySchema:
            - AttributeName: GSI3PK
              KeyType: HASH
            - AttributeName: GSI3SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI4
          KeySchema:
            - AttributeName: GSI4PK
              KeyType: HASH
            - AttributeName: GSI4SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # ---- S3 Buckets ----
  FileStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-files'
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT]
            AllowedOrigins: ['*']
            MaxAge: 3600

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-frontend'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub '${FrontendBucket.Arn}/*'

  # ---- Lambda Layer ----
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub '${AWS::StackName}-shared'
      ContentUri: layers/shared/
      CompatibleRuntimes:
        - python3.12

  # ---- API Gateway ----
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  # ---- Lambda Functions ----
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/auth/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FileShareTable
      Events:
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /auth/login
            Method: post
        Logout:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /auth/logout
            Method: post
        ChangePassword:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /auth/change-password
            Method: post
        SeedAdmin:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /auth/seed-admin
            Method: post

  UsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/users/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FileShareTable
      Events:
        CreateUser:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /users
            Method: post
        ListUsers:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /users
            Method: get
        UpdateUser:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /users/{username}
            Method: put
        DeleteUser:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /users/{username}
            Method: delete

  FoldersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/folders/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FileShareTable
        - S3CrudPolicy:
            BucketName: !Ref FileStorageBucket
      Events:
        CreateFolder:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /folders
            Method: post
        ListFolders:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /folders
            Method: get
        DeleteFolder:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /folders/{folderId}
            Method: delete
        AssignFolders:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /folders/assignments
            Method: post
        UnassignFolders:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /folders/assignments
            Method: delete

  FilesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/files/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FileShareTable
        - S3CrudPolicy:
            BucketName: !Ref FileStorageBucket
      Events:
        ListFiles:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /files
            Method: get
        UploadUrl:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /files/upload-url
            Method: post
        DownloadUrl:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /files/download-url
            Method: post
        FileVersions:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /files/{folderId}/{fileName}/versions
            Method: get

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${Api}.execute-api.${AWS::Region}.amazonaws.com/prod'
  FrontendUrl:
    Description: Frontend website URL
    Value: !GetAtt FrontendBucket.WebsiteURL
  TableName:
    Description: DynamoDB table name
    Value: !Ref FileShareTable
  FileBucket:
    Description: File storage bucket name
    Value: !Ref FileStorageBucket
